### ISSUE TITLE
Running locally with Minikube

### ISSUE THREAD

**Issue by Chris0lsen** [mruoss/flame_k8s_backend#50]
Hi, and first of all great work on this backend! I'm trying to test it out in my local environment with minikube. I built a minimal application using the `flame_k8s_backend` and my k8s cluster is having trouble provisioning runners:

```
stream logs failed container "runner" in pod "flame-test-deployment-6664d8567c-hmtsn-8t6fz" is waiting to start: trying and failing to pull image for flame-namespace/flame-test-deployment-6664d8567c-hmtsn-8t6fz (runner)
```

I'm guessing it's trying to go to Docker hub to fetch my image, instead of looking in my minikube docker env registry? Nothing in the `k8s_client` code screams this to me, but my `flame-test` pods fire up without issue, and it's only the `runners` that fail. I feel like I'm missing something trivial :) Any advice?

The part of my `deployment.yaml` that describes my application:

```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: flame-test-deployment
    namespace: flame-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flame-test
  template:
    metadata:
      labels:
        app: flame-test
    spec:
      serviceAccountName: flame-test
      containers:
      - name: flame-test
        image: flame_test:latest
        ports:
        - containerPort: 4099
        - containerPort: 4369
        - containerPort: 9100
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace 
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: RELEASE_DISTRIBUTION
          value: name
        - name: RELEASE_NODE
          value: flame_test@$(POD_IP)
        - name: RELEASE_COOKIE
          value: "secret"
```

Thanks in advance!
